import type { Dish } from "./types.ts";

export const DISHES: readonly Dish[] = [
  {
    id: "carbonara",
    name: "Carbonara Pasta",
    plateEmoji: "🍝",
    combo: ["cheese", "bacon", "pasta"],
    flavorText: "Silky, salty, and gone in five minutes.",
    recipe: {
      ingredients: [
        "300g spaghetti",
        "150g bacon or guanciale, diced",
        "3 egg yolks + 1 whole egg",
        "60g pecorino or parmesan, finely grated",
        "Lots of black pepper",
        "Salt for the pasta water",
      ],
      steps: [
        "Boil the spaghetti in well-salted water until just shy of al dente.",
        "Meanwhile, fry the bacon over medium heat until crisp; keep the fat in the pan.",
        "Whisk the eggs, cheese, and a heavy grind of pepper in a bowl.",
        "Drop the drained pasta into the pan off the heat, then stir in the egg mixture with a splash of pasta water.",
        "Toss until glossy — the residual heat cooks the sauce. Serve immediately with more cheese.",
      ],
    },
  },
  {
    id: "meat-pot-pie",
    name: "Meat Pot Pie",
    plateEmoji: "🥧",
    combo: ["meat", "potato", "flour"],
    flavorText: "A roof of pastry over a stew worth protecting.",
    recipe: {
      ingredients: [
        "500g stewing beef, cubed",
        "2 potatoes, diced",
        "1 onion + 2 carrots, chopped",
        "2 tbsp flour, plus pastry (shop-bought is fine)",
        "500ml beef stock",
        "1 tbsp Worcestershire sauce, thyme, salt, pepper",
      ],
      steps: [
        "Brown the beef in batches, then soften the onion and carrots in the same pot.",
        "Stir in the flour, then the stock, Worcestershire, and thyme; simmer 1 hour.",
        "Add the potatoes and simmer 20 more minutes until the stew is thick.",
        "Spoon into a pie dish, lid with pastry, crimp, and cut a steam vent.",
        "Bake at 200°C / 400°F for 25–30 minutes until deep golden.",
      ],
    },
  },
  {
    id: "oyakodon",
    name: "Oyakodon Bowl",
    plateEmoji: "🍛",
    combo: ["chicken", "rice", "egg"],
    flavorText: "Chicken and egg, reunited over rice.",
    recipe: {
      ingredients: [
        "2 chicken thighs, sliced",
        "3 eggs, lightly beaten",
        "1 onion, thinly sliced",
        "150ml dashi (or light chicken stock)",
        "2 tbsp soy sauce + 2 tbsp mirin + 1 tsp sugar",
        "Steamed rice, to serve",
      ],
      steps: [
        "Simmer the dashi, soy, mirin, and sugar in a small pan.",
        "Add the onion and chicken; simmer 6–8 minutes until cooked through.",
        "Pour the eggs over in a spiral and cover for about a minute — barely set is perfect.",
        "Slide the whole thing over a bowl of hot rice.",
        "Top with scallions or a shake of shichimi if you have it.",
      ],
    },
  },
  {
    id: "loco-moco",
    name: "Loco Moco",
    plateEmoji: "🍚",
    combo: ["rice", "meat", "egg"],
    flavorText: "A burger patty, gravy, and a fried egg walk onto rice.",
    recipe: {
      ingredients: [
        "400g ground beef, formed into 2 patties",
        "2 eggs",
        "Steamed rice, to serve",
        "1 onion, sliced, for the gravy",
        "250ml beef stock + 1 tbsp flour + 1 tbsp butter",
        "Soy sauce, salt, pepper",
      ],
      steps: [
        "Season and sear the patties to your liking; set aside.",
        "In the same pan, brown the onion in butter, stir in the flour, then whisk in the stock and a dash of soy until it's gravy.",
        "Fry the eggs sunny-side up.",
        "Stack: rice, patty, gravy, egg on top.",
        "Break the yolk. That's the whole point.",
      ],
    },
  },
  {
    id: "margherita-pizza",
    name: "Margherita Pizza",
    plateEmoji: "🍕",
    combo: ["cheese", "flour", "tomato"],
    flavorText: "Three ingredients, one flag, zero regrets.",
    recipe: {
      ingredients: [
        "300g bread flour + 1 tsp yeast + 1 tsp salt + 200ml warm water",
        "200g crushed tomatoes (passata)",
        "125g fresh mozzarella, torn",
        "Fresh basil leaves",
        "Olive oil, salt",
      ],
      steps: [
        "Mix the dough, knead 8 minutes, and let it rise 1–2 hours until doubled.",
        "Heat the oven as hot as it goes with a tray or stone inside.",
        "Stretch the dough thin, top with tomato, a pinch of salt, and the mozzarella.",
        "Bake 7–10 minutes until blistered.",
        "Finish with basil and a drizzle of olive oil.",
      ],
    },
  },
  {
    id: "bolognese",
    name: "Spaghetti Bolognese",
    plateEmoji: "🍝",
    combo: ["meat", "pasta", "tomato"],
    flavorText: "Sunday afternoon in a pot.",
    recipe: {
      ingredients: [
        "400g ground beef (or beef + pork)",
        "400g canned tomatoes",
        "350g spaghetti",
        "1 onion + 1 carrot + 1 celery stick, finely diced",
        "2 garlic cloves, splash of red wine or milk",
        "Olive oil, oregano, salt, pepper, parmesan to serve",
      ],
      steps: [
        "Soften the onion, carrot, and celery in olive oil; add garlic.",
        "Brown the meat hard — let it catch a little.",
        "Add tomatoes, a splash of wine or milk, and oregano; simmer low for 45+ minutes.",
        "Cook the spaghetti; save a cup of pasta water.",
        "Toss pasta and sauce with a splash of that water; serve buried in parmesan.",
      ],
    },
  },
  {
    id: "croque-madame",
    name: "Croque Madame",
    plateEmoji: "🥪",
    combo: ["bread", "cheese", "egg"],
    flavorText: "A grilled cheese that went to finishing school.",
    recipe: {
      ingredients: [
        "4 slices good white bread",
        "150g gruyère or comté, grated",
        "2 slices ham (optional but traditional)",
        "2 eggs",
        "Béchamel: 1 tbsp butter + 1 tbsp flour + 150ml milk",
        "Dijon mustard, nutmeg, salt",
      ],
      steps: [
        "Make a quick béchamel: melt butter, stir in flour, whisk in milk until thick; season with nutmeg.",
        "Spread bread with mustard, layer ham and most of the cheese, and close the sandwiches.",
        "Top each with béchamel and the rest of the cheese.",
        "Bake or broil until bubbling and bronzed.",
        "Fry the eggs and crown each sandwich with one.",
      ],
    },
  },
  {
    id: "kedgeree",
    name: "Kedgeree",
    plateEmoji: "🍚",
    combo: ["egg", "fish", "rice"],
    flavorText: "Smoky rice with a colonial-era passport.",
    recipe: {
      ingredients: [
        "300g smoked haddock (or any smoked fish)",
        "250g basmati rice",
        "3 eggs, soft-boiled",
        "1 onion, sliced + 2 tsp curry powder",
        "50g butter, handful of parsley",
        "Lemon wedges, salt, pepper",
      ],
      steps: [
        "Poach the fish in water or milk for 8 minutes; keep the liquid and flake the fish.",
        "Cook the rice in the poaching liquid topped up with water.",
        "Fry the onion in butter with the curry powder until golden.",
        "Fold rice, fish, and onion together; season well.",
        "Top with halved soft-boiled eggs, parsley, and lemon.",
      ],
    },
  },
  {
    id: "pancakes",
    name: "Fluffy Pancakes",
    plateEmoji: "🥞",
    combo: ["egg", "flour", "milk"],
    flavorText: "Breakfast's most reliable applause line.",
    recipe: {
      ingredients: [
        "200g flour + 2 tsp baking powder + 2 tbsp sugar + pinch of salt",
        "1 egg",
        "250ml milk",
        "2 tbsp melted butter, plus more for the pan",
        "Maple syrup, to serve",
      ],
      steps: [
        "Whisk the dry ingredients; whisk the egg, milk, and butter separately.",
        "Combine with a few lazy strokes — lumps are fine, overmixing is not.",
        "Rest the batter 5 minutes while the pan heats over medium.",
        "Ladle in rounds; flip when bubbles pop and stay open.",
        "Stack, butter, drown in syrup.",
      ],
    },
  },
  {
    id: "lava-cake",
    name: "Chocolate Lava Cake",
    plateEmoji: "🍰",
    combo: ["chocolate", "egg", "flour"],
    flavorText: "Undercooked on purpose, celebrated for it.",
    recipe: {
      ingredients: [
        "120g dark chocolate",
        "100g butter, plus more for the ramekins",
        "2 eggs + 2 yolks",
        "60g sugar",
        "2 tbsp flour",
        "Pinch of salt, cocoa for dusting",
      ],
      steps: [
        "Melt the chocolate and butter together; cool slightly.",
        "Whisk eggs, yolks, and sugar until pale and thick.",
        "Fold in the chocolate, then the flour and salt.",
        "Divide between buttered, cocoa-dusted ramekins.",
        "Bake at 220°C / 425°F for 10–12 minutes — edges set, center wobbly. Invert and serve fast.",
      ],
    },
  },
  {
    id: "apple-fritters",
    name: "Apple Fritters",
    plateEmoji: "🍩",
    combo: ["apple", "egg", "flour"],
    flavorText: "The fair came to your kitchen.",
    recipe: {
      ingredients: [
        "2 apples, peeled and chopped",
        "150g flour + 1 tsp baking powder",
        "1 egg",
        "100ml milk",
        "1 tsp cinnamon + 2 tbsp sugar",
        "Neutral oil for frying, powdered sugar to finish",
      ],
      steps: [
        "Whisk the flour, baking powder, cinnamon, and sugar.",
        "Add the egg and milk to make a thick batter, then fold in the apples.",
        "Heat 2cm of oil to about 175°C / 350°F.",
        "Fry spoonfuls 2–3 minutes per side until deep brown.",
        "Drain on paper and bury in powdered sugar.",
      ],
    },
  },
  {
    id: "loaded-baked-potato",
    name: "Loaded Baked Potato",
    plateEmoji: "🥔",
    combo: ["bacon", "cheese", "potato"],
    flavorText: "A potato living its absolute best life.",
    recipe: {
      ingredients: [
        "2 large russet potatoes",
        "100g cheddar, grated",
        "4 rashers bacon, fried and crumbled",
        "Sour cream and chives",
        "Butter, olive oil, flaky salt, pepper",
      ],
      steps: [
        "Rub the potatoes with oil and salt; bake at 200°C / 400°F for about an hour until the skin crackles.",
        "Fry the bacon until crisp; crumble it.",
        "Split the potatoes, fluff the insides with a fork, and work in a knob of butter.",
        "Pile on cheese while hot so it melts, then bacon.",
        "Finish with sour cream, chives, and black pepper.",
      ],
    },
  },
  {
    id: "bacon-egg-sando",
    name: "Bacon & Egg Sando",
    plateEmoji: "🥪",
    combo: ["bacon", "bread", "egg"],
    flavorText: "The reason alarms get snoozed only once.",
    recipe: {
      ingredients: [
        "2 slices thick white bread or a soft roll",
        "3 rashers bacon",
        "2 eggs",
        "Butter, mayo",
        "Hot sauce or ketchup — pick a side",
        "Salt, pepper",
      ],
      steps: [
        "Fry the bacon until it shatters; leave the fat.",
        "Fry the eggs in the bacon fat, basting the whites.",
        "Toast and butter the bread; add a thin coat of mayo.",
        "Stack bacon, then eggs; season.",
        "Sauce it, close it, eat it over the plate — the yolk is coming.",
      ],
    },
  },
  {
    id: "shakshuka",
    name: "Shakshuka",
    plateEmoji: "🍳",
    combo: ["bread", "egg", "tomato"],
    flavorText: "Eggs poached in a slow-simmered argument of spices.",
    recipe: {
      ingredients: [
        "400g canned tomatoes",
        "4 eggs",
        "Crusty bread, for mopping",
        "1 onion + 1 red pepper, sliced",
        "2 garlic cloves, 1 tsp cumin, 1 tsp paprika, chili flakes",
        "Olive oil, salt, feta and parsley to finish (optional)",
      ],
      steps: [
        "Soften the onion and pepper in olive oil; add garlic and spices.",
        "Add the tomatoes and simmer 10–15 minutes until thick.",
        "Make wells and crack in the eggs; cover and cook until the whites set.",
        "Scatter with feta and parsley.",
        "Serve in the pan with bread as the only cutlery.",
      ],
    },
  },
  {
    id: "arroz-con-pollo",
    name: "Arroz con Pollo",
    plateEmoji: "🥘",
    combo: ["chicken", "rice", "tomato"],
    flavorText: "One pot, whole household fed, zero complaints.",
    recipe: {
      ingredients: [
        "4 chicken thighs",
        "300g rice",
        "200g crushed tomatoes",
        "1 onion + 1 pepper + 3 garlic cloves",
        "600ml chicken stock, pinch of saffron or 1 tsp turmeric",
        "Olive oil, paprika, salt, peas and olives to finish",
      ],
      steps: [
        "Brown the seasoned chicken in olive oil; set aside.",
        "Soften the onion, pepper, and garlic; add paprika and tomatoes.",
        "Stir in the rice, then the stock and saffron; nestle the chicken on top.",
        "Cover and simmer low ~20 minutes until the rice drinks the stock.",
        "Rest 5 minutes; scatter peas and olives over.",
      ],
    },
  },
  {
    id: "fish-and-chips",
    name: "Fish and Chips",
    plateEmoji: "🍟",
    combo: ["fish", "flour", "potato"],
    flavorText: "Fried in batter, wrapped in nostalgia.",
    recipe: {
      ingredients: [
        "2 white fish fillets (cod or haddock)",
        "4 potatoes, cut into thick chips",
        "150g flour + 1 tsp baking powder + 200ml cold sparkling water",
        "Neutral oil for frying",
        "Salt, malt vinegar, lemon",
      ],
      steps: [
        "Fry the chips at 140°C / 285°F until soft but pale; drain.",
        "Whisk the flour, baking powder, and cold fizzy water into a thin batter.",
        "Dust the fish in flour, dip in batter, and fry at 180°C / 350°F until golden.",
        "Refry the chips at 180°C until crisp.",
        "Salt everything aggressively; serve with vinegar and lemon.",
      ],
    },
  },
  {
    id: "rice-pudding",
    name: "Rice Pudding",
    plateEmoji: "🍮",
    combo: ["egg", "milk", "rice"],
    flavorText: "Dessert that doubles as a hug.",
    recipe: {
      ingredients: [
        "150g short-grain rice",
        "750ml whole milk",
        "1 egg yolk",
        "60g sugar",
        "1 tsp vanilla, cinnamon, pinch of salt",
        "Knob of butter",
      ],
      steps: [
        "Simmer the rice in the milk with sugar and salt, stirring often, ~25 minutes.",
        "When creamy, temper the egg yolk with a spoonful of the hot pudding and stir it back in.",
        "Cook 2 more minutes; add vanilla and butter.",
        "Serve warm or chilled.",
        "Dust with cinnamon either way.",
      ],
    },
  },
  {
    id: "chocolate-bread-pudding",
    name: "Chocolate Bread Pudding",
    plateEmoji: "🍫",
    combo: ["bread", "chocolate", "milk"],
    flavorText: "Stale bread's redemption arc.",
    recipe: {
      ingredients: [
        "300g day-old bread, torn",
        "150g dark chocolate, chopped",
        "500ml milk (or half cream)",
        "2 eggs + 80g sugar",
        "1 tsp vanilla, pinch of salt",
        "Butter for the dish",
      ],
      steps: [
        "Warm the milk and melt in half the chocolate.",
        "Whisk in eggs, sugar, vanilla, and salt.",
        "Toss the bread and remaining chocolate in a buttered dish; pour the custard over and soak 15 minutes.",
        "Bake at 180°C / 350°F for 30–35 minutes until just set.",
        "Serve warm — cream optional, encouraged.",
      ],
    },
  },
  {
    id: "cheeseburger",
    name: "Cheeseburger",
    plateEmoji: "🍔",
    combo: ["bread", "cheese", "meat"],
    flavorText: "Perfected in a parking lot, honored forever.",
    recipe: {
      ingredients: [
        "400g ground beef (20% fat), 2 loose balls",
        "2 soft buns",
        "2 slices American or cheddar cheese",
        "Onion, pickles, lettuce, tomato as you like",
        "Mustard, ketchup or burger sauce",
        "Salt, pepper",
      ],
      steps: [
        "Get a skillet screaming hot; toast the buns in it first.",
        "Smash the beef balls flat, season, and don't touch for 2 minutes.",
        "Flip, cheese immediately, cook 1 more minute.",
        "Sauce the buns, stack with the extras.",
        "Eat while the cheese still moves.",
      ],
    },
  },
  {
    id: "chicken-katsu",
    name: "Chicken Katsu",
    plateEmoji: "🍗",
    combo: ["chicken", "egg", "flour"],
    flavorText: "Crunch you can hear from the next room.",
    recipe: {
      ingredients: [
        "2 chicken breasts, butterflied and flattened",
        "50g flour",
        "1 egg, beaten",
        "100g panko breadcrumbs",
        "Neutral oil for shallow frying",
        "Tonkatsu sauce (or Worcestershire + ketchup), shredded cabbage",
      ],
      steps: [
        "Season the chicken; set up flour, egg, and panko stations.",
        "Coat each piece: flour, then egg, then a firm press into panko.",
        "Shallow-fry in 1cm of oil, 3–4 minutes per side, until deep gold.",
        "Rest on a rack, then slice into strips.",
        "Serve over cabbage with a flood of tonkatsu sauce.",
      ],
    },
  },
  {
    id: "mac-and-cheese",
    name: "Mac and Cheese",
    plateEmoji: "🧀",
    combo: ["cheese", "milk", "pasta"],
    flavorText: "Comfort, measured in cheese pulls.",
    recipe: {
      ingredients: [
        "300g macaroni",
        "250g cheddar (plus gruyère if fancy), grated",
        "500ml milk",
        "3 tbsp butter + 3 tbsp flour",
        "1 tsp mustard powder, pinch of nutmeg, salt, pepper",
        "Breadcrumbs for the top (optional)",
      ],
      steps: [
        "Boil the macaroni 2 minutes short of the packet time.",
        "Melt butter, stir in flour, then whisk in milk until it thickens.",
        "Off the heat, melt in the cheese with mustard and nutmeg.",
        "Fold in the pasta; pour into a dish, top with breadcrumbs.",
        "Bake at 190°C / 375°F for 20 minutes until bronzed and bubbling.",
      ],
    },
  },
  {
    id: "beef-stew",
    name: "Hearty Beef Stew",
    plateEmoji: "🍲",
    combo: ["meat", "potato", "tomato"],
    flavorText: "Patience you can eat with a spoon.",
    recipe: {
      ingredients: [
        "600g stewing beef, cubed",
        "3 potatoes, chunked",
        "2 tbsp tomato paste + 200g chopped tomatoes",
        "1 onion + 2 carrots + 2 garlic cloves",
        "500ml beef stock, splash of red wine",
        "Bay leaf, thyme, salt, pepper, olive oil",
      ],
      steps: [
        "Brown the beef in batches; don't crowd the pot.",
        "Soften the onion, carrots, and garlic; stir in the tomato paste.",
        "Return the beef with tomatoes, stock, wine, and herbs; simmer low 1.5 hours.",
        "Add the potatoes and cook 30 more minutes.",
        "Season, rest 10 minutes, serve with bread you'll pretend is for dipping.",
      ],
    },
  },
  {
    id: "apple-cheddar-melt",
    name: "Apple Cheddar Melt",
    plateEmoji: "🥪",
    combo: ["apple", "bread", "cheese"],
    flavorText: "Sweet, sharp, and suspiciously sophisticated.",
    recipe: {
      ingredients: [
        "4 slices sourdough or country bread",
        "150g sharp cheddar, sliced",
        "1 crisp apple, thinly sliced",
        "Butter for the outside",
        "1 tsp Dijon mustard or a drizzle of honey",
        "Pinch of black pepper",
      ],
      steps: [
        "Butter the outsides of the bread; spread mustard (or honey) inside.",
        "Layer cheese, apple, more cheese — the cheese glues the apple in.",
        "Grind over a little pepper and close the sandwiches.",
        "Cook in a skillet over medium-low, pressing gently, 3–4 minutes per side.",
        "Rest one minute before slicing so the melt holds.",
      ],
    },
  },
  {
    id: "french-toast",
    name: "French Toast",
    plateEmoji: "🍞",
    combo: ["bread", "egg", "milk"],
    flavorText: "Yesterday's bread, today's headliner.",
    recipe: {
      ingredients: [
        "4 thick slices day-old bread (brioche if you have it)",
        "2 eggs",
        "150ml milk",
        "1 tsp vanilla + 1 tsp cinnamon + 1 tbsp sugar",
        "Butter for the pan",
        "Maple syrup and berries, to serve",
      ],
      steps: [
        "Whisk the eggs, milk, vanilla, cinnamon, and sugar in a shallow dish.",
        "Soak each slice about 20 seconds per side.",
        "Melt butter over medium heat and fry 2–3 minutes per side until golden.",
        "Keep warm in a low oven while the rest cook.",
        "Serve with syrup and berries.",
      ],
    },
  },
];
